### ISSUE TITLE
LevelFilter deserialization case-sensitive when deserializing from a config::Config

### ISSUE THREAD

**Issue by cdhowie** [rust-lang/log#532]
When deserializing from a [`config::Config`](https://docs.rs/config/0.13.2/config/struct.Config.html), `log::LevelFilter` deserialization is case-sensitive, even though it appears it should not be.

Cargo.toml:

```toml
[package]
name = "rust-tinker"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
config = "0.13"
```

main.rs:

```rust
use std::error::Error;

use log::LevelFilter;

#[derive(PartialEq, Eq, Debug, serde::Deserialize)]
struct Example {
    level: log::LevelFilter,
}

fn main() -> Result<(), Box<dyn Error>> {
    let config = config::Config::builder()
        .set_default("level", "debug")?
        .build()?;

    assert_eq!(
        Example { level: LevelFilter::Debug },
        config.try_deserialize()?
    );

    Ok(())
}
```

No output is expected.

Actual output:

```
Error: enum LevelFilter does not have variant constructor debug
```

The only casing that appears to be accepted is all uppercase -- using `"DEBUG"` works.

`log::Level` suffers from the same problem, and I'd expect the fix to be similar.
