### ISSUE TITLE
Structured logging doesn't seem to work

### ISSUE THREAD

**Issue by svanharmelen** [rust-lang/log#540]
Hi 👋🏻 I'm trying write structured logs, but somehow the key/values seem to be ignored...

I have this in my `Cargo.toml`:
```toml
[dependencies]
env_logger = "0.10"
log = { version = "0.4.17", features = ["kv_unstable"] }
```

And this is `main.rs`:
```rust
use log::info;

fn main() {
    env_logger::builder()
        .filter_level(log::LevelFilter::Info)
        .init();
    info!(some = "thing"; "Hello, world!");
}
```

And when I run this I get this:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/4171547/208921456-31508247-3aa7-4be0-84b6-ae6d38fcf306.png">

Any ideas? Am I missing anything or doing something wrong?

Thanks!
